#!/bin/bash

# This step requires the following software
#module load gcc/6.2.0
#module load python/3.5.3


# Activate the environment
conda activate TWAS


# Change the working directory
cd $HOME/Project2026/Myproject_AD/00_prep_inputs_for_metaxcan/code/


# Create the output directory
mkdir $HOME/Project2026/Myproject_AD/00_prep_inputs_for_metaxcan/output/metaxcan_gwas_imputed/


# Run summary_imputation_post_process (merge the gwas_impute_regions files into a single file!)
# First, echo the following command to prevent errors

# Run the post_process workflow
python3 $HOME/TWAS/Breast-cancer-Example/summary-gwas-imputation/src/gwas_summary_imputation_postprocess.py \
-gwas_file $HOME/Project2026/Myproject_AD/00_prep_inputs_for_metaxcan/output/metaxcan_gwas_parse/final_metal_ad_kunkle_pgcalz_ukb1_EUR.txt.gz \
-folder $HOME/Project2026/Myproject_AD/00_prep_inputs_for_metaxcan/output/metaxcan_gwas_impute_regions/ \
-pattern final_metal_ad_kunkle_pgcalz_ukb1_EUR_* \
-parsimony 9 \
-output $HOME/Project2026/Myproject_AD/00_prep_inputs_for_metaxcan/output/metaxcan_gwas_imputed/final_metal_ad_kunkle_pgcalz_ukb.txt.gz











