#!/bin/bash

#该步骤需要如下软件
#module load gcc/6.2.0
#module load python/3.5.3

#激活小环境
conda activate TWAS

#更改路径
cd $HOME/Project2026/Myproject_AD/00_prep_inputs_for_metaxcan/code/

#创建输出文件夹
mkdir $HOME/Project2026/Myproject_AD/00_prep_inputs_for_metaxcan/output/metaxcan_gwas_impute_regions/

#进行插补summary_imputation

#运行 bash 脚本
echo ./030_run_summary_imputation.sh # 检查代码有无错误
#bash ./030_run_summary_imputation.sh
#nohup bash ./030_run_summary_imputation.sh > temp/summary_imputation.log &
#taskset -c 0-9 bash ./030_run_summary_imputation.sh
taskset -c 0-9 nohup bash ./030_run_summary_imputation.sh > temp/summary_imputation.log 2>&1 &

#查看运行进程，有无报错
tail -f temp/summary_imputation.log
less temp/summary_imputation.log # -->按 shift + F 浮动查看进程





****************将以下内容复制到 bash 脚本**********************************************************************************************
#!/bin/bash

# 限制脚本自身使用前10个核心
#taskset -c 0-9 bash "$0" "$@"
#exit 0  # 这行后面的代码是实际要执行的内容


#执行插补
for CHR in {1..22}
do
	for SB in {0..9}
	do
		python3 $HOME/TWAS/Breast-cancer-Example/summary-gwas-imputation/src/gwas_summary_imputation.py \
		-by_region_file $HOME/TWAS/Breast-cancer-Example/data/reference/eur_ld.bed.gz \
		-gwas_file $HOME/Project2026/Myproject_AD/00_prep_inputs_for_metaxcan/output/metaxcan_gwas_parse/final_metal_ad_kunkle_pgcalz_ukb1_EUR.txt.gz \
		-parquet_genotype $HOME/TWAS/Breast-cancer-Example/data/reference/reference_panel_1000G/chr${CHR}.variants.parquet \
		-parquet_genotype_metadata $HOME/TWAS/Breast-cancer-Example/data/reference/reference_panel_1000G/variant_metadata.parquet \
		-window 100000 \
		-parsimony 9 \
		-chromosome ${CHR} \
		-regularization 0.1 \
		-frequency_filter 0.01 \
		-sub_batches 10 \
		-sub_batch ${SB} \
		--standardise_dosages \
		-output $HOME/Project2026/Myproject_AD/00_prep_inputs_for_metaxcan/output/metaxcan_gwas_impute_regions/final_metal_ad_kunkle_pgcalz_ukb1_EUR_chr${CHR}_sb${SB}_reg0.1_ff0.01_by_region.txt.gz
	done
done




********************************************************************************************
* 代码参数说明：https://github.com/hakyimlab/summary-gwas-imputation/wiki/GWAS-Harmonization-And-Imputation
-parsimony 9 # 与计算精度、数值稳定性或输出压缩级别有关；在遗传学大数据的矩阵运算中，降低精度可以加速计算并节省内存，但可能影响结果准确性，数值越大，精度越高。
                      # 输出文件压缩级别，控制压缩比，范围通常为 1–9：低值（1–3）：压缩快，文件较大；高值（7–9）：压缩慢，文件较小。
	        # 与正则化协同：-regularization 0.1 已经对效应值进行了收缩，因此 -parsimony 可以设置得稍宽松，让正则化去处理冗余，而简约性参数主要控制极端过拟合。








