#!/bin/bash
#PBS -l walltime=01:00:00
#PBS -l mem=20GB
#PBS -l ncpus=1

# This script formats input GWAS sumstats
# need to be in the GCTA-COJO .ma format = header row of SNP A1 A2 freq b se p N
# SNP identifier (rsID), effect allele, other allele, frequency of effect allele,
# effect size, standard error, p-value and sample size


### Environment ###




### Preamble ###

directory=/media/desk15/iy2120/Project2026/Myproject_AD/02_sex_stratified_gwas/050_SBayesS/

input_GWAMA=(/media/desk15/iy2120/Project2026/Myproject_AD/02_sex_stratified_gwas/020_Meta_analysis/Females/Metaanalysis_ad_female_AllCohorts_QCed_rsID.txt /media/desk15/iy2120/Project2026/Myproject_AD/02_sex_stratified_gwas/020_Meta_analysis/Males/Metaanalysis_ad_male_AllCohorts_QCed_rsID.txt)


### Run script ###

cd ${directory}


for i in "${!input_GWAMA[@]}"
do

    name_GWAMA=$(echo ${input_GWAMA[$i]} | sed 's|.*/020_Meta_analysis/.*/||' | sed 's|_QCed_rsID.txt||')

    # Format sex-stratified GWAS Meta-analysis sumstats

    awk 'NR==1 {print "SNP A1 A2 freq b se p N"} \
    NR>1 {print $16, toupper($2), toupper($3), $4, $8, $9, $10, $12}' \
    ${input_GWAMA[$i]} \
    > ${name_GWAMA}_formatted_SBayes.ma

done

















```
nohup bash 01_b_Format_sumstats_GWAMA.sh >01_b_Format_sumstats_GWAMA.log 2>&1 &
```








