#!/bin/bash
#PBS -l walltime=24:00:00
#PBS -l mem=350GB
#PBS -l ncpus=15

# This script uses SBayesS in GCTB to calculate SNP-based heritability


### Environment ###

module load gctb/2.5.2


### Preamble ###

directory=/media/desk15/iy2120/Project2026/Myproject_AD/02_sex_stratified_gwas/050_SBayesS/

LD_matrix=/media/desk15/iy2120/Project2026/Myproject_AD/02_sex_stratified_gwas/sex_stratified_data/ldm_ukb_50k_bigset_2.8M/ukb_50k_bigset_2.8M/ukb50k_2.8M_shrunk_sparse.mldmlist # chr 1 - 22, doesn't include X chr

GWAS_sumstats=(${directory}*_formatted_SBayes.ma) # need to be in the GCTA-COJO .ma format = header row of SNP A1 A2 freq b se p N


### Submit script ###

cd ${directory} || exit 1


for i in "${!GWAS_sumstats[@]}"
do

    name=$(basename "${GWAS_sumstats[$i]}" | sed 's|_formatted_SBayes.ma||')

    /media/desk15/iy2120/Genomic_tools/gctb_2.5.2_Linux/gctb --sbayes S \
     --mldm ${LD_matrix} \
     --gwas-summary ${GWAS_sumstats[$i]} \
     --thread 15 \
     --chain-length 25000 \
     --burn-in 5000 \
     --num-chains 4 \
     --thin 10 \
     --seed 37904 \
     --write-mcmc-txt \
     --out ${name}_SBayesS_redomcmc

done

# *.parRes gives overall results
# Pi = polygenicity
# hsq = h2 = SNP-based heritability
# S = relationship between MAF and effect size (A negative relationship between effect size and MAF is a signature of negative (or purifying) selection)





















```
nohup bash 03_a_SBayesS_h2.sh >03_a_SBayesS_h2.log 2>&1 &
```



