#!/bin/bash


conda activate TWAS

# Create the output directory
mkdir -p /media/desk15/iy2120/Project2026/Myproject_AD/04_acat_eqtl_sqtl/output/acat_eqtl/


# Create two files: all_tissues.txt and 14tiss.txt

# Create the study_list and tiss_list files
cp /media/desk15/iy2120/Project2026/Myproject_AD/03_spredixcan_eqtl_sqtl/temp/gwas_imputed_files /media/desk15/iy2120/Project2026/Myproject_AD/04_acat_eqtl_sqtl/temp/
mv /media/desk15/iy2120/Project2026/Myproject_AD/04_acat_eqtl_sqtl/temp/gwas_imputed_files  /media/desk15/iy2120/Project2026/Myproject_AD/04_acat_eqtl_sqtl/temp/study_list

cd /media/desk15/iy2120/Project2026/Myproject_AD/04_acat_eqtl_sqtl/tissue_lists/
ls *.txt | sed 's/.txt//g' > /media/desk15/iy2120/Project2026/Myproject_AD/04_acat_eqtl_sqtl/temp/tiss_list


# Run the Bash script to perform the ACAT-O analysis
cd /media/desk15/iy2120/Project2026/Myproject_AD/04_acat_eqtl_sqtl/code/

****************Copy the following content into the Bash script**********************************
#!/bin/bash

tiss_list=$(cat /media/desk15/iy2120/Project2026/Myproject_AD/04_acat_eqtl_sqtl/temp/tiss_list)
echo ${tiss_list}

study_list=$(cat /media/desk15/iy2120/Project2026/Myproject_AD/04_acat_eqtl_sqtl/temp/study_list)
echo ${study_list}

# Run the ACAT-O analysis
for TISSUE in ${tiss_list}
do
	for STUDY in ${study_list}
	do
		python3 /media/desk15/iy2120/Genomic_tools/MetaXcan/software/spredixcan_expression_acat.py \
		--results_dir /media/desk15/iy2120/Project2026/Myproject_AD/03_spredixcan_eqtl_sqtl/output/spredixcan_eqtl_mashr/ \
		--study_pattern "spredixcan_igwas_gtexmashrv8_${STUDY}*" \
		--tiss_list /media/desk15/iy2120/Project2026/Myproject_AD/04_acat_eqtl_sqtl/tissue_lists/${TISSUE}.txt \
		--output /media/desk15/iy2120/Project2026/Myproject_AD/04_acat_eqtl_sqtl/output/acat_eqtl/${TISSUE}__${STUDY}_eqtl_acat_results.tsv
	done
done
******************************************************************************

echo ./010_run_acat_eqtl.sh # Check the script for errors
#bash ./010_run_acat_eqtl.sh
nohup bash ./010_run_acat_eqtl.sh > ../temp/010_run_acat_eqtl.log &


# Monitor the job
tail -f ../temp/010_run_acat_eqtl.log
















