#!/bin/bash
#PBS -l walltime=00:15:00
#PBS -l mem=5GB
#PBS -l ncpus=1


# This script uses LD score regression to format summary stats with munge - for gene by environment results
# Then the munged summary stats go in to calculate the LDSC intercept

### Environment ###

#module load ldsc/20190815

### Preamble ###

# Edit below variables for your specific LDSC

directory=/media/desk15/iy2120/Project2026/Myproject_AD/02_sex_stratified_gwas/010_Format_sumstats/GxS/fulldc/ # working directory

reference=/media/desk15/iy2120/Project2026/Myproject_AD/02_sex_stratified_gwas/sex_stratified_data/LDSC_reference/ # location of reference directory



### Submit script ###

source activate LDSC
cd ${directory}

# rather than doing in parallel just do each manually
# They don't take long to run and there are differences depending on if the input sumstats contain the imputation score
# From LDSC docs: Imputation quality is correlated with LD Score, and low imputation quality yields lower test statistics, so imputation quality is a confounder for LD Score regression. To prevent bias from variable imputation quality, we usually remove poorly-imputed SNPs by filtering on INFO > 0.9. The scz and bip summary statistics that we're using for this tutorial have INFO columns, so munge_sumstats.py will automatically perform the filtering. If you're using summary statistics that don't come with an INFO column, we recommend filtering to HapMap3 SNPs (using the --merge or --merge-alleles flags), because these seem to be well-imputed in most studies.
# For All Of Us set info to 1 for all SNPs as was whole genome sequenced
# Blokland21 has no info column so use advice to restrict to hapmap SNPs and don't  filter on info


mkdir Munged_sumstats

# ADNI

munge_sumstats.py \
 --sumstats adni_ad_GxS_fulldc_sumstats_formatted_formetaanalysis_transformed.txt \
 --merge-alleles ${reference}w_hm3.noMHC.snplist \
 --snp rsID_build37 \
 --frq FREQA1 \
 --signed-sumstats Z,0 \
 --p P_G_by_E \
 --ignore MARKER_build37,MAF \
 --out Munged_sumstats/adni_ad_GxS_fulldc_sumstats_formatted_formetaanalysis_transformed_LDSC_munged



# MSBB

munge_sumstats.py \
 --sumstats msbb_ad_GxS_fulldc_sumstats_formatted_formetaanalysis_transformed.txt \
 --merge-alleles ${reference}w_hm3.noMHC.snplist \
 --snp rsID_build37 \
 --frq FREQA1 \
 --signed-sumstats Z,0 \
 --p P_G_by_E \
 --ignore MARKER_build37,MAF \
 --out Munged_sumstats/msbb_ad_GxS_fulldc_sumstats_formatted_formetaanalysis_transformed_LDSC_munged


# ROSMAP

munge_sumstats.py \
 --sumstats rosmap_ad_GxS_fulldc_sumstats_formatted_formetaanalysis_transformed.txt \
 --merge-alleles ${reference}w_hm3.noMHC.snplist \
 --snp rsID_build37 \
 --frq FREQA1 \
 --signed-sumstats Z,0 \
 --p P_G_by_E \
 --ignore MARKER_build37,MAF \
 --out Munged_sumstats/rosmap_ad_GxS_fulldc_sumstats_formatted_formetaanalysis_transformed_LDSC_munged





















```bash
nohup bash 06_a_LDSC_munge.sh >06_a_LDSC_munge.log 2>&1 &
```













