#!/bin/bash
#PBS -l walltime=01:30:00
#PBS -l mem=150GB
#PBS -l ncpus=1
#PBS -J 0-5

# This script matches each sumstats file to the reference dbSNP file (build 37 and 38 combined with SNPs only MAF > = 0.0001 to make this run in a reasonable timeframe but without dropping SNPs)
# As its SNPs only this will remove any indels etc
# It gives each SNP a consistent markername to use in the meta-analysis and converts between builds
# Here most of the cohorts are build 37, with two build 38 so convert all to build 37

### Preamble ###

directory=/media/desk15/iy2120/Project2026/Myproject_AD/02_sex_stratified_gwas/010_Format_sumstats/Females/output # This is where the plots will be output

dbSNP=/media/desk15/iy2120/Project2026/Myproject_AD/02_sex_stratified_gwas/sex_stratified_data/dbSNP155/NCBI_Hsapiens_dbSNP155_GRCh37_GRCh38.p13_split_multiallelics_MAF0_0001_ALL_matches.txt

files=/media/desk15/iy2120/Project2026/Myproject_AD/02_sex_stratified_gwas/010_Format_sumstats/Females/input/*_ad_female_sumstats.txt

#name=$(echo ${files} | sed 's/\/media\/desk15\/iy2120\/Project2026\/Myproject_AD\/02_sex_stratified_gwas\/010_Format_sumstats\/Females\/input\///g' | sed 's/_build37_ad_female_sumstats.txt//g')

### Run script ###

source activate GWAS
cd /media/desk15/iy2120/Project2026/Myproject_AD/02_sex_stratified_gwas/010_Format_sumstats/Females/input/

# Check if the input file name contains "build37" or "build38" and run the appropriate block of code
# MarkerName is then created based on the dbSNP ref file so it is consistent across all cohort sumstats so corrcet matching occurs in the meta-analysis
# Note that MarkerName is in the format CHR:BP:Allele:Allele but doesn't necessarily match to A1:A2 (alleles are not flipped - but this is not a problem as METAL deals with allele flipping)
for FILE in ${files}
do
name=$(echo ${FILE} | sed 's/\/media\/desk15\/iy2120\/Project2026\/Myproject_AD\/02_sex_stratified_gwas\/010_Format_sumstats\/Females\/input\///g' | sed 's/_build37_ad_female_sumstats.txt//g')

if [[ "${FILE}" == *"build37"* ]]; then
    echo "Processing file for build 37: ${FILE}"
    awk 'NR==FNR {
            marker[$1,$2,$4,$5]=$10;
            rsid[$1,$2,$4,$5]=$3;
            next
         }
         {
            if (FNR == 1)
                print $0,"MARKER_build37","rsID_build37";
            else if (($1,$2,$3,$4) in marker)
                print $0,marker[$1,$2,$3,$4],rsid[$1,$2,$3,$4];
            else if (($1,$2,$4,$3) in marker)
                print $0,marker[$1,$2,$4,$3],rsid[$1,$2,$4,$3];
            else
                print $0,"missing","missing";
         }' ${dbSNP} ${FILE} > ${directory}/${name}_ad_female_sumstats_formatted.txt


elif [[ "${FILE}" == *"build38"* ]]; then
    echo "Processing file for build 38: ${FILE}"
    awk 'NR==FNR {
            marker[$6,$7,$8,$9]=$10;
            rsid[$6,$7,$8,$9]=$3;
            next
         }
         {
            if (FNR == 1)
                print $0,"MARKER_build37","rsID_build37";
            else if (($1,$2,$3,$4) in marker)
                print $0,marker[$1,$2,$3,$4],rsid[$1,$2,$3,$4];
            else if (($1,$2,$4,$3) in marker)
                print $0,marker[$1,$2,$4,$3],rsid[$1,$2,$4,$3];
            else
                print $0,"missing","missing";
         }' ${dbSNP} ${FILE} > ${directory}/${name}_ad_female_sumstats_formatted.txt
else
    echo "Error: Unrecognized build in file name: ${FILE}. Skipping."
fi
done















```bash
nohup bash 02_Match_to_dbSNP_ref_file.sh >02_Match_to_dbSNP_ref_file.log 2>&1 &
```




