#!/bin/bash
#PBS -l walltime=00:30:00
#PBS -l mem=20GB
#PBS -l ncpus=1
#PBS -J 0-5

# After matching each sumstats file to the reference dbSNP file (build 37 and 38 combined with SNPs only MAF > = 0.0001) to get a consistent marker name
# Check these files


### Preamble ###

directory=/media/desk15/iy2120/Project2026/Myproject_AD/02_sex_stratified_gwas/010_Format_sumstats/Females/output # This is where the plots will be output

files=${directory}/*_ad_female_sumstats_formatted.txt

#name=$(echo ${files} | sed 's/\/media\/desk15\/iy2120\/Project2026\/Myproject_AD\/02_sex_stratified_gwas\/010_Format_sumstats\/Females\/output\///g' | sed 's/_ad_female_sumstats_formatted.txt//g')


### Run script ###

source activate GWAS
cd /media/desk15/iy2120/Project2026/Myproject_AD/02_sex_stratified_gwas/010_Format_sumstats/Females/output/


for FILE in ${files}
do
name=$(echo ${FILE} | sed 's/\/media\/desk15\/iy2120\/Project2026\/Myproject_AD\/02_sex_stratified_gwas\/010_Format_sumstats\/Females\/output\///g' | sed 's/_ad_female_sumstats_formatted.txt//g')

echo "Checking file: ${FILE}" > ${name}_ad_female_sumstats_check_formatted_file.txt


## Check how many SNPs did not match to marker name ##

echo "Number rows missing (including non-SNPs):" >> ${name}_ad_female_sumstats_check_formatted_file.txt
grep -c "missing" ${FILE} >> ${name}_ad_female_sumstats_check_formatted_file.txt
echo "" >> ${name}_ad_female_sumstats_check_formatted_file.txt

echo "Number rows missing (SNPs only):" >> ${name}_ad_female_sumstats_check_formatted_file.txt 
awk '$13 == "missing" && length($3) == 1 && length($4) == 1' ${FILE} | wc -l >> ${name}_ad_female_sumstats_check_formatted_file.txt
echo "" >> ${name}_ad_female_sumstats_check_formatted_file.txt

echo "Number rows with \"no_match\" (SNP present in the reference dbSNP file but not in the particular build using):" >> ${name}_ad_female_sumstats_check_formatted_file.txt
grep -c "no_match" ${FILE} >> ${name}_ad_female_sumstats_check_formatted_file.txt
echo "" >> ${name}_ad_female_sumstats_check_formatted_file.txt

echo "Number rows with \"no_rsid\" (SNP present in one build, mapped to the other build and coords found but no matching rsid found):" >> ${name}_ad_female_sumstats_check_formatted_file.txt
grep -c "no_rsid" ${FILE} >> ${name}_ad_female_sumstats_check_formatted_file.txt
echo "" >> ${name}_ad_female_sumstats_check_formatted_file.txt



## Remove lines with no match to dbSNP reference file ##

awk '($13 != "missing" && !($13 ~ /^no_match/) && $14 != "no_rsid") {print}' ${FILE} > ${name}_ad_female_sumstats_formatted_formetaanalysis.txt



## Check min and max of each column to see if anything weird ##

# Before removing missing lines

echo "Min and max of each column before removing missing lines" >> ${name}_ad_female_sumstats_check_formatted_file.txt
awk 'NR==1 {
        for (i=1; i<=NF; i++)
            headers[i] = $i  # Store column headers in an array
     }
     NR > 1 {
        for (i=1; i<=NF; i++) {
            if (NR == 2 || $i < min[i]) {  # Update min value for each column
                min[i] = $i
                minHeader[i] = headers[i]  # Store corresponding header
            }
            if (NR == 2 || $i > max[i]) {  # Update max value for each column
                max[i] = $i
                maxHeader[i] = headers[i]  # Store corresponding header
            }
        }
     }
     END {
        for (i=1; i<=NF; i++) {
            print "Min value for column " headers[i] ": " min[i]
            print "Max value for column " headers[i] ": " max[i]
        }
     }' ${FILE} >> ${name}_ad_female_sumstats_check_formatted_file.txt
echo "" >> ${name}_ad_female_sumstats_check_formatted_file.txt


# After removing missing lines
echo "Min and max of each column after removing missing lines" >> ${name}_ad_female_sumstats_check_formatted_file.txt
awk 'NR==1 {
        for (i=1; i<=NF; i++)
            headers[i] = $i  # Store column headers in an array
     }
     NR > 1 {
        for (i=1; i<=NF; i++) {
            if (NR == 2 || $i < min[i]) {  # Update min value for each column
                min[i] = $i
                minHeader[i] = headers[i]  # Store corresponding header
            }
            if (NR == 2 || $i > max[i]) {  # Update max value for each column
                max[i] = $i
                maxHeader[i] = headers[i]  # Store corresponding header
            }
        }
     }
     END {
        for (i=1; i<=NF; i++) {
            print "Min value for column " headers[i] ": " min[i]
            print "Max value for column " headers[i] ": " max[i]
        }
     }' ${name}_ad_female_sumstats_formatted_formetaanalysis.txt >> ${name}_ad_female_sumstats_check_formatted_file.txt
echo "" >> ${name}_ad_female_sumstats_check_formatted_file.txt




# Check lowest p-value retained after matching consistent marker
# Check QC on MAF and info done correctly

done















```bash
nohup bash 03_Check_formatted_sumstats.sh >03_Check_formatted_sumstats.log 2>&1 &
```