#!/bin/bash
#PBS -l walltime=00:30:00
#PBS -l mem=15GB
#PBS -l ncpus=1
#PBS -J 0-5

# This script creates Manhattan and QQ Plots from the GWAS summary statistics (using all SNPs)

### Environment ###

#module load R/4.2.0


### Preamble ###

directory=/media/desk15/iy2120/Project2026/Myproject_AD/02_sex_stratified_gwas/010_Format_sumstats/Females/output # This is where the plots will be output

p_threshold=5e-08 # p-value threshold for GWAS (where horizontal line will be placedon manhattan plot): 5e-08 for only common variants or 5e-09 for rare and common variants

files=${directory}/*_ad_female_sumstats_formatted_formetaanalysis.txt

#name=$(echo ${files} | sed 's/\/media\/desk15\/iy2120\/Project2026\/Myproject_AD\/02_sex_stratified_gwas\/010_Format_sumstats\/Females\/output\///g' | sed 's/_ad_female_sumstats_formatted_formetaanalysis.txt//g')


### Run script ###

source activate GWAS
cd ${directory}

for FILE in ${files}
do
name=$(echo ${FILE} | sed 's/\/media\/desk15\/iy2120\/Project2026\/Myproject_AD\/02_sex_stratified_gwas\/010_Format_sumstats\/Females\/output\///g' | sed 's/_ad_female_sumstats_formatted_formetaanalysis.txt//g')

# First change chr X for 23 so plots OK
awk '{ gsub("X", "23", $1) ; print }' ${FILE} > ${name}_temp.txt


Rscript --vanilla ../code/04_Plots_Man_QQ.R ${name}_temp.txt ${name}_ad_female_sumstats_formatted_formetaanalysis ${p_threshold} 

rm ${name}_temp.txt

done















```bash
nohup bash 04_Plots_Man_QQ.sh >04_Plots_Man_QQ.log 2>&1 &
```





